(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Programm: dummy
 * Datei: dummyCyclic.st
 * Autor: awalz
 * Erstellt: 26. Juni 2014
 ********************************************************************
 * Implementierung des Programms dummy
 ********************************************************************)

PROGRAM _CYCLIC


(* TODO : Code hier einfügen *)


END_PROGRAM
