(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: UserSpilke
 * Datei: FB_MASTERMODUL.st
 * Autor: Awalz
 * Erstellt: 25. März 2014
 ********************************************************************
 * Implementierung der Library UserSpilke
 ********************************************************************) 

(*<$Description$> TODO: Bitte Kommentar hier einzufügen </$Description$>*)
FUNCTION_BLOCK FB_MASTERMODUL
END_FUNCTION_BLOCK