(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: Bibliothek
 * Datei: FB_DUBBLEUUNWINDERDATA.st
 * Autor: awalz
 * Erstellt: 24. Juni 2014
 ********************************************************************
 * Implementierung der Library Bibliothek
 ********************************************************************) 

(* TODO: Bitte Kommentar hier einfügen *)
FUNCTION_BLOCK FB_DUBBLEUUNWINDERDATA
END_FUNCTION_BLOCK