(********************************************************************
 * COPYRIGHT -- Nitto
 ********************************************************************
 * Programm: MAIN
 * Datei: FB_MARK_POSITION.st
 * Autor: s_spilker
 * Erstellt: 9. November 2015
 ********************************************************************
 * Implementierung des Programms MAIN
 ********************************************************************) 

(* TODO: Bitte Kommentar hier einfügen *)
FUNCTION_BLOCK FB_MARK_POSITION
END_FUNCTION_BLOCK