(********************************************************************
 * COPYRIGHT -- Nitto
 ********************************************************************
 * Programm: MAIN
 * Datei: FB_SyncData.st
 * Autor: s_spilker
 * Erstellt: 9. November 2015
 ********************************************************************
 * Implementierung des Programms MAIN
 ********************************************************************) 

(* TODO: Bitte Kommentar hier einfügen *)
FUNCTION_BLOCK FB_SyncData
END_FUNCTION_BLOCK