(********************************************************************
 * COPYRIGHT -- Bernecker + Rainer
 ********************************************************************
 * Program: VisuTasks
 * File: VisuTasksInit.st
 * Author: schoenefeldr
 * Created: August 01, 2012
 ********************************************************************
 * Implementation of program VisuTasks
 ********************************************************************)

PROGRAM _INIT


calibrateDiam		:= CALIB_UNDEFINED;

END_PROGRAM

