(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: Bibliothek
 * Datei: FB_CONST_AXISSTATE.st
 * Autor: awalz
 * Erstellt: 26. August 2014
 ********************************************************************
 * Implementierung der Library Bibliothek
 ********************************************************************) 

(* TODO: Bitte Kommentar hier einfügen *)
FUNCTION_BLOCK FB_CONST_AXIS_STATE
END_FUNCTION_BLOCK