(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: Bibliothek
 * Datei: FB_CONST_AXIS_ACTIONS.st
 * Autor: Awalz
 * Erstellt: 1. April 2014
 ********************************************************************
 * Implementierung der Library Bibliothek
 ********************************************************************) 

 (*<$Description$> TODO: Bitte Kommentar hier einzufügen </$Description$>*)
FUNCTION_BLOCK FB_CONST_AXIS_ACTIONS
END_FUNCTION_BLOCK