(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: Bibliothek
 * Datei: FB_CONST_CUTTINGUNIT_ERRORS.st
 * Autor: okrebs
 * Erstellt: 23. Mai 2014
 ********************************************************************
 * Implementierung der Library Bibliothek
 ********************************************************************) 

(* TODO: Bitte Kommentar hier einzufügen *)
FUNCTION_BLOCK FB_CONST_CUTTINGUNIT_ERRORS
END_FUNCTION_BLOCK