(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: Bibliothek
 * Datei: FB_CONST_MACHINE_MODE.st
 * Autor: Awalz
 * Erstellt: 31. März 2014
 ********************************************************************
 * Implementierung der Library Bibliothek
 ********************************************************************) 

 (*<$Description$> TODO: Bitte Kommentar hier einzufügen </$Description$>*)
FUNCTION_BLOCK FB_CONST_MACHINE_MODES
END_FUNCTION_BLOCK