(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: Bibliothek
 * Datei: FB_Clk.st
 * Autor: Awalz
 * Erstellt: 30. April 2014
 ********************************************************************
 * Implementierung der Library Bibliothek
 ********************************************************************) 

 (*<$Description$> TODO: Bitte Kommentar hier einzufügen </$Description$>*)
FUNCTION_BLOCK FB_Clk
	c200();
	c500();
	c1000();
	c5000();
END_FUNCTION_BLOCK