(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: Bibliothek
 * Datei: FB_SwitchCabinet.st
 * Autor: awalz
 * Erstellt: 18. Juli 2014
 ********************************************************************
 * Implementierung der Library Bibliothek
 ********************************************************************) 

(* TODO: Bitte Kommentar hier einfügen *)
FUNCTION_BLOCK FB_SwitchCabinet
EMCY_Buttons();
END_FUNCTION_BLOCK