(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: Bibliothek
 * Datei: FB_PACKBELT_DATA.st
 * Autor: okrebs
 * Erstellt: 10. Januar 2017
 ********************************************************************
 * Implementierung der Library Bibliothek
 ********************************************************************) 

(* TODO: Bitte Kommentar hier einfügen *)
FUNCTION_BLOCK FB_PACKBELT_DATA
END_FUNCTION_BLOCK