(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Programm: MAIN
 * Datei: FB_BUFFER_RECIPE_DATA.st
 * Autor: awalz
 * Erstellt: 26. November 2014
 ********************************************************************
 * Implementierung des Programms MAIN
 ********************************************************************) 

(* TODO: Bitte Kommentar hier einfügen *)
FUNCTION_BLOCK FB_BUFFER_RECIPE_DATA
END_FUNCTION_BLOCK