(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: UserSpilke
 * Datei: FB_MainHW.st
 * Autor: Awalz
 * Erstellt: 26. März 2014
 ********************************************************************
 * Implementierung der Library UserSpilke
 ********************************************************************) 

(*<$Description$> TODO: Bitte Kommentar hier einzufügen </$Description$>*)
FUNCTION_BLOCK FB_MainHW
END_FUNCTION_BLOCK