(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Library: UserSpilke
 * Datei: FB_MainCtrl.st
 * Autor: Awalz
 * Erstellt: 24. März 2014
 ********************************************************************
 * Implementierung der Library UserSpilke
 ********************************************************************) 

(* TODO: Daten FB dient als Datenstruktur *)
FUNCTION_BLOCK FB_MainCtrl
END_FUNCTION_BLOCK