(********************************************************************
 * COPYRIGHT -- Bernecker + Rainer
 ********************************************************************
 * Library: UserSpilke
 * File: SPR_MoveMaster.st
 * Author: knausenbergl
 * Created: December 14, 2012
 ********************************************************************
 * Implementation of library UserSpilke
 ********************************************************************) 

(*<$Description$> Starts a movement of the master axis </$Description$>*)
FUNCTION_BLOCK SPR_MoveMaster
END_FUNCTION_BLOCK