(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Programm: MAIN
 * Datei: FB_PULLBRAEKUNIT.st
 * Autor: Awalz
 * Erstellt: 27. März 2014
 ********************************************************************
 * Implementierung des Programms MAIN
 ********************************************************************) 

(*<$Description$> TODO: Bitte Kommentar hier einzufügen </$Description$>*)
FUNCTION_BLOCK FB_PULLBREAKUNIT
END_FUNCTION_BLOCK